config/routes.rb
Rails.application.routes.draw do
  resources :operations

    match '/home', to: 'static_pages#home',  via: 'get'
    match '/help',	to: 'static_pages#help',  via: 'get'
    match '/about',   to: 'static_pages#about',  via: 'get'
    match '/contact', to: 'static_pages#contact',  via: 'get'

  resources :instructors

  resources :onlines

  resources :areas

  resources :users

  resources :documents

    root :to => 'static_pages#home'

end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
  
  # Validar que los atributos sean obligatorios
  
    validates :document_id, :presence => true
    validates :number_document, :presence => true
    validates :name, :presence => true
    validates :last_name, :presence => true
    validates :email, :presence => true 
    validates :area_id, :presence => true
    validates :user_id, :presence => true
    validates :online_id, :presence => true
  
  # validar un atributo booleano
  
    # validates :genero, inclusion: [true, false]
  
  # validar que un atributos unicos
  
   validates :document_id, uniqueness: { message: "No se puede Repetir" }
   validates :number_document, uniqueness: { message: "No se puede Repetir" }
   validates :email, uniqueness: { message: "No se puede Repetir" }

  # validar formato de un email
  
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i,
  message: 'Formato no valido' } 
  
  # valida la longitud de un campo, tanto la longitud minima como la maxima
  
  validates :number_document, length: { minimum: 5, maximum: 30 }
  validates :name, length: { minimum: 5, maximum: 50 }
  validates :last_name, length: { minimum: 5, maximum: 50 }
  
  # Valida si un atributo es numerico
  
  validates :document_id, numericality: true
  validates :number_document, numericality: true
  
  belongs_to :document
  belongs_to :area
  belongs_to :user
  belongs_to :online
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, only: [:show, :edit, :update, :destroy]

  # GET /instructors
  # GET /instructors.json
  def index
    @instructors = Instructor.all
  end

  # GET /instructors/1
  # GET /instructors/1.json
  def show
  end

  # GET /instructors/new
  def new
    @instructor = Instructor.new
  end

  # GET /instructors/1/edit
  def edit
  end

  # POST /instructors
  # POST /instructors.json
  def create
    @instructor = Instructor.new(instructor_params)

    respond_to do |format|
      if @instructor.save
        format.html { redirect_to @instructor, notice: 'Instructor was successfully created.' }
        format.json { render :show, status: :created, location: @instructor }
      else
        format.html { render :new }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instructors/1
  # PATCH/PUT /instructors/1.json
  def update
    respond_to do |format|
      if @instructor.update(instructor_params)
        format.html { redirect_to @instructor, notice: 'Instructor was successfully updated.' }
        format.json { render :show, status: :ok, location: @instructor }
      else
        format.html { render :edit }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructors/1
  # DELETE /instructors/1.json
  def destroy
    @instructor.destroy
    respond_to do |format|
      format.html { redirect_to instructors_url, notice: 'Instructor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instructor
      @instructor = Instructor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instructor_params
      params.require(:instructor).permit(:document_id, :number_document, :name, :last_name, :gender, :street_address, :email, :phone, :area_id, :user_id, :online_id)
    end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_form.html.erb
<%= form_for(@instructor) do |f|  %>
  <% if @instructor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>

      <ul>
      <% @instructor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :documento_id %><br>
    <%= f.text_field :document_id %>
  </div>
  <div class="field">
    <%= f.label :numero_documento %><br>
    <%= f.text_field :number_document %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :apellido %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :genero %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :direccion %><br>
    <%= f.text_field :street_address %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :telefono %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :area_id %><br>
    <%= f.text_field :area_id %>
  </div>
  <div class="field">
    <%= f.label :rol_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :linea_id %><br>
    <%= f.text_field :online_id %>
  </div>
  <div class="actions" >
    <%= f.submit  "Crear"%>
  </div>
<% end %>

app/views/instructors/edit.html.erb
<h1>Editar instructor</h1>

<%= render 'form' %>

<%= link_to 'ver', @instructor %> |
<%= link_to 'atras', instructors_path %>

app/views/instructors/index.html.erb
<h1>Listado de  instructores</h1>

<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Documento</th>
      <th>Numero documento</th>
      <th>Nombres</th>
      <th>Apellidos</th>
      <th>Genero</th>
      <th>Direccion</th>
      <th>Email</th>
      <th>Telefono</th>
      <th>Area</th>
      <th>Rol</th>
      <th>Linea</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instructors.each do |instructor| %>
      <tr>
        <td><%= instructor.document %></td>
        <td><%= instructor.number_document %></td>
        <td><%= instructor.name %></td>
        <td><%= instructor.last_name %></td>
        <td><%= instructor.gender %></td>
        <td><%= instructor.street_address %></td>
        <td><%= instructor.email %></td>
        <td><%= instructor.phone %></td>
        <td><%= instructor.area %></td>
        <td><%= instructor.user %></td>
        <td><%= instructor.online %></td>
        <td><%= link_to 'Ver', instructor %></td>
        <td><%= link_to 'Editar', edit_instructor_path(instructor) %></td>
        <td><%= link_to 'Eliminar', instructor, method: :delete, data: { confirm: 'Seguro desea Eliminar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Instructor', new_instructor_path %>

app/views/instructors/new.html.erb
<h1>Nuevo instructor</h1>

<%= render 'form' %>

<%= link_to 'Atras', instructors_path %>

app/views/instructors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Documento:</strong>
  <%= @instructor.document %>
</p>

<p>
  <strong>Numero documento:</strong>
  <%= @instructor.number_document %>
</p>

<p>
  <strong>Nombres:</strong>
  <%= @instructor.name %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @instructor.last_name %>
</p>

<p>
  <strong>Genero:</strong>
  <%= @instructor.gender %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @instructor.street_address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @instructor.email %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @instructor.phone %>
</p>

<p>
  <strong>Area:</strong>
  <%= @instructor.area %>
</p>

<p>
  <strong>Rol:</strong>
  <%= @instructor.user %>
</p>

<p>
  <strong>Linea:</strong>
  <%= @instructor.online %>
</p>

<%= link_to 'Editar', edit_instructor_path(@instructor) %> |
<%= link_to 'Atras', instructors_path %>