config/routes.rb
Rails.application.routes.draw do
  resources :operations

    match '/home', to: 'static_pages#home',  via: 'get'
    match '/help',	to: 'static_pages#help',  via: 'get'
    match '/about',   to: 'static_pages#about',  via: 'get'
    match '/contact', to: 'static_pages#contact',  via: 'get'

  resources :instructors

  resources :onlines

  resources :areas

  resources :users

  resources :documents

    root :to => 'static_pages#home'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    By Stiven Sanchez <br>
    And Omar Salas .... Todos los derechos reservados © 2014 ::.
  </small>
</footer>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     <%= link_to 'INICIO', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to "Instructor", instructors_path %></li>
<li><%= link_to "Documentos", documents_path %></li>
<li><%= link_to "Roles", users_path %></li>
<li><%= link_to "Areas", areas_path %></li>
<li><%= link_to "Lineas", onlines_path %></li>
<li><%= link_to "Operaciones", operations_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Myt" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Myt" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>