config/routes.rb
Rails.application.routes.draw do
  resources :operations

    match '/home', to: 'static_pages#home',  via: 'get'
    match '/help',	to: 'static_pages#help',  via: 'get'
    match '/about',   to: 'static_pages#about',  via: 'get'
    match '/contact', to: 'static_pages#contact',  via: 'get'

  resources :instructors

  resources :onlines

  resources :areas

  resources :users

  resources :documents

    root :to => 'static_pages#home'

end

app/models/operation.rb
class Operation < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>" , :thumb => "100x100>" }, :default_url => "/images/:style/foto.png"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
   # Validar que los atributos sean obligatorios
  
    validates :area_id, :presence => true
    validates :maquina, :presence => true
    validates :name, :presence => true
    validates :time_standar, :presence => true
    validates :description, :presence => true
    
  
  belongs_to :area
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :set_operation, only: [:show, :edit, :update, :destroy]

  # GET /operations
  # GET /operations.json
  def index
    @operations = Operation.all
  end

  # GET /operations/1
  # GET /operations/1.json
  def show
  end

  # GET /operations/new
  def new
    @operation = Operation.new
  end

  # GET /operations/1/edit
  def edit
  end

  # POST /operations
  # POST /operations.json
  def create
    @operation = Operation.new(operation_params)

    respond_to do |format|
      if @operation.save
        format.html { redirect_to @operation, notice: 'Operation was successfully created.' }
        format.json { render :show, status: :created, location: @operation }
      else
        format.html { render :new }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operations/1
  # PATCH/PUT /operations/1.json
  def update
    respond_to do |format|
      if @operation.update(operation_params)
        format.html { redirect_to @operation, notice: 'Operation was successfully updated.' }
        format.json { render :show, status: :ok, location: @operation }
      else
        format.html { render :edit }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operations/1
  # DELETE /operations/1.json
  def destroy
    @operation.destroy
    respond_to do |format|
      format.html { redirect_to operations_url, notice: 'Operation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operation
      @operation = Operation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def operation_params
      params.require(:operation).permit(:name, :area_id, :description, :maquina, :time_standar, :image)
    end
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/views/operations/_form.html.erb
<%= form_for(@operation) do |f| %>
  <% if @operation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@operation.errors.count, "error") %> prohibited this operation from being saved:</h2>

      <ul>
      <% @operation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :area %><br>
    <%= f.text_field :area_id %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :maquina %><br>
    <%= f.text_field :maquina %>
  </div>
  <div class="field">
    <%= f.label :tiempo_estandar %><br>
    <%= f.text_field :time_standar %>
  </div>
<div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit "Crear" %>
  </div>
<% end %>

app/views/operations/edit.html.erb
<h1>Editar operacion</h1>

<%= render 'form' %>

<%= link_to 'Ver', @operation %> |
<%= link_to 'Atras', operations_path %>

app/views/operations/index.html.erb
<h1>Listado de operaciones</h1>

<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Image</th>
      <th>Nombre</th>
      <th>Area</th>
      <th>Descripcion</th>
      <th>Maquina</th>
      <th>Tempo estandar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @operations.each do |operation| %>
      <tr>
        <td><%=image_tag operation.image.url(:thumb)%></td>
        <td><%= operation.name %></td>
        <td><%= operation.area %></td>
        <td><%= operation.description %></td>
        <td><%= operation.maquina %></td>
        <td><%= operation.time_standar %></td>
        <td><%= link_to 'Ver', operation %></td>
        <td><%= link_to 'Editar', edit_operation_path(operation) %></td>
        <td><%= link_to 'Eliminar', operation, method: :delete, data: { confirm: 'Esta seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Operacion', new_operation_path %>

app/views/operations/new.html.erb
<h1>Nueva operacion</h1>

<%= render 'form' %>

<%= link_to 'Atras', operations_path %>

app/views/operations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @operation.name %>
</p>

<p>
  <strong>Area:</strong>
  <%= @operation.area %>
</p>
<%=image_tag@operation.image.url(:thumb)%>
<p>
  <strong>Descripcion:</strong>
  <%= @operation.description %>
</p>

<p>
  <strong>Maquina:</strong>
  <%= @operation.maquina %>
</p>

<p>
  <strong>Tiempo estandar:</strong>
  <%= @operation.time_standar %>
</p>

<%= link_to 'Editar', edit_operation_path(@operation) %> |
<%= link_to 'Atras', operations_path %>